version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: sikowali1-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: sikowali_user
      POSTGRES_PASSWORD: sikowali_pass
      POSTGRES_DB: sikowali1
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
